version: '2'

services:
  portal:
    image: sybdata/portal
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - /opt/stalker/stalker_portal:/var/www/stalker_portal
      - /opt/stalker/stalker_portal/epg:/var/www/stalker_portal/epg
    depends_on:
      - db
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=stalker_db
      - MYSQL_USER=stalker
      - MYSQL_PASSWORD=stalkerpass
    volumes:
      - /opt/stalker/mysql_data:/var/lib/mysql
